Code
kosttiq/Lab2 pull request #3
Opened 2022-04-27 18:26 UTC by Vlads165

2022-04-27 20:04 UTC, rsyomen requested changes

2022-04-27 20:04 UTC, rsyomen commented on code.cpp
> +    for (int i = 1; i < k; i++) {
i = 0

2022-04-27 20:04 UTC, rsyomen commented on code.cpp
> +void sort(flight_data* massiv, int k) {
сделай другим методом, как в задании сказано

2022-04-27 20:04 UTC, rsyomen commented on code.cpp
> +        massiv_2[k].city = "";
massiv_2[i] не k

2022-04-27 20:04 UTC, rsyomen commented on code.cpp
> +}
добавь наш бизнес-план по рентабельности пожалуйста

2022-04-28 10:50 UTC, Vlads165 commented on code.cpp
> +        massiv_2[k].city = "";
Окок

2022-04-28 10:50 UTC, Vlads165 commented on code.cpp
> +void sort(flight_data* massiv, int k) {
Я сделаю вставками

2022-04-28 10:50 UTC, Vlads165 commented on code.cpp
> +}
Хорошо

2022-04-28 11:00 UTC, rsyomen approved these changes

2022-04-28 11:00 UTC, rsyomen commented on code.cpp
> +}
все работает!

2022-04-28 11:00 UTC, merged